image:
    file: .gitpod.Dockerfile

tasks:
    - before: |
          alias g=git
          git config l=log --graph
          git config alias.uncommit '!.banksh/bin/git-uncommit'
          git config alias.wip '!.banksh/bin/git-wip'
          git config alias.cm '!GIT_MESSAGE_PREFIX= .banksh/bin/git-wip'
      init: |
          ln -sf /usr/local/cargo/bin/* /workspace/.cargo/bin/*
          cargo build || echo failed
          cargo build --release || echo failed
    - before: |
          mkdir -p target/doc
      command: |
          cargo doc || echo failed
          http --port 8081 target/doc

ports:
    - port: 8081
      onOpen: open-preview

vscode:
    extensions:
        - matklad.rust-analyzer@0.4.0-dev:sJgqBE+kHIaVKLid8xlZJg==
        - vadimcn.vscode-lldb@1.5.3:vTh/rWhvJ5nQpeAVsD20QA==
