image:
    file: dev.Dockerfile

tasks:
    - before: |
          alias g=git
          git config alias.l 'log --graph'
          git config alias.uncommit '!.banksh/bin/git-uncommit'
          git config alias.cm '!GIT_MESSAGE_PREFIX= .banksh/bin/git-wip'
          git config alias.wip '!.banksh/bin/git-wip'
          git config alias.wipe '!.banksh/bin/git-wipe'
      init: |
          mkdir -p /workspace/.cargo/bin
          ln -sf /usr/local/cargo/bin/* /workspace/.cargo/bin
      command: |
          mkdir -p ./target/doc
          cargo doc || printf 'Non-critical task failed with exit status %s.\n' "$?"
          cd ./target/doc
          basic-http-server -xa 0.0.0.0:8081 .
    - init: |
      prebuild: |
          cargo build || printf 'Non-critical task failed with exit status %s.\n' "$?"
          cargo build --release || printf 'Non-critical task failed with exit status %s.\n' "$?"
      command: |
          cargo check || printf 'Non-critical task failed with exit status %s.\n' "$?"
          pwd
          ls --color

ports:
    - port: 8081
      onOpen: open-preview
