#!/bin/bash
set -euo pipefail
shopt -s inherit_errexit nullglob compat"${BASH_COMPAT=42}"

declare repo
repo="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

cd "$repo"

declare parent
parent="$(git rev-parse HEAD)"

function icao-hex  {
    declare letters="$*"
    for (( i=0; i<${#letters}; i++ )); do
        if (( i > 0 )); then
            printf " "
        fi
        declare letter="${letters:$i:1}"
        declare phono
        phono="${icao_hex[$letter]}"
        printf "%s" "$phono"
    done
}

declare -rA icao_hex=(
    [0]=zero
    [1]=one
    [2]=two
    [3]=three
    [4]=four
    [5]=five
    [6]=six
    [7]=seven
    [8]=eight
    [9]=nine
    [a]=alfa
    [b]=bravo
    [c]=charlie
    [d]=delta
    [e]=echo
    [f]=foxtrot
)

git add .

declare parent_author_timestamp
parent_author_timestamp="$(git log --format=%at -1)"

declare tree
tree="$(git write-tree)"

declare icao_tree
icao_tree="$(icao-hex "${tree:0:4}")"

declare -a git_roots
git_roots+=( "$(git rev-list --max-parents=0 "$parent")" )

declare -i generation=0
for root in "${git_roots[@]}"; do
    declare -i root_generation;
    root_generation="$(git rev-list --count "$root"..."$parent")"
    if ((root_generation >= generation)); then
        generation=$((root_generation + 1))
    fi 
done

declare message
message="wip r$generation $icao_tree"

declare current_timestamp
current_timestamp="$(date +%s)"

declare -i timestamp=$((parent_author_timestamp + 20 * 60 + 20))
declare date
date="$(date -ud @"$timestamp")"

export GIT_COMMITTER_DATE="$date"
export GIT_AUTHOR_DATE="$date"
git commit --no-edit -m "$message"

git --no-pager log --format=raw --graph --decorate -n 2
