#!/bin/bash
eval "$(cat "$(dirname -- "$0")/lib/base")"
# shellcheck source=lib/base
source /dev/null

# Installs/updates .banksh as a git subtree in another repository.
# https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt

if [[ "$__owd__" == "$__dir__" ]]; then
  echo "FATAL: Run this from the root of a repo you want to install/update into."
  exit 1
fi

set -x

cd "$__owd__"

# Ensure we're at the root of a git repository
test -d .git
git status

declare path=.banksh
declare repo=https://github.com/jeremyBanks/banksh
declare head=HEAD

if [[ $(git status --porcelain) ]]; then
  echo ".banksh/update error: working tree must be clean"
  git status
  exit 1
fi

if [[ -d $path ]]; then
  if ! GIT_EDITOR="bash -c 'git log -1 --pretty=%B HEAD^2 > \"\$1\"' --" git subtree pull --squash --prefix="$path" "$repo" "$head"; then
    git rm -rf .banksh
    git commit .banksh -m "Removed '.banksh/'"
    git subtree add --squash --prefix="$path" "$repo" "$head"
  fi
else
  git subtree add --squash --prefix="$path" "$repo" "$head"
fi

git --no-pager log --graph --all --decorate -n8 --oneline

echo "Done"
