name: Rust

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --workspace --verbose
      - run: cargo test --workspace --verbose
      - run: cargo test --benches --workspace --verbose
      - run: cargo clippy
      - run: cargo doc
